apiVersion: v2
name: image-patcher
description: Helm chart for image-patch-operator, a Kubernetes operator that builds patched container images from ImagePatch CRs using Kaniko.
type: application
version: 0.3.38
appVersion: "v0.1.49"
kubeVersion: ">=1.21.0-0"
keywords:
  - kaniko
  - image
  - operator
  - kubebuilder
sources:
  - https://github.com/pinclr/image-patcher
maintainers:
  - name: pinclr
