//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AptConfig) DeepCopyInto(out *AptConfig) {
	*out = *in
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AptConfig.
func (in *AptConfig) DeepCopy() *AptConfig {
	if in == nil {
		return nil
	}
	out := new(AptConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildOptions) DeepCopyInto(out *BuildOptions) {
	*out = *in
	if in.SingleSnapshot != nil {
		in, out := &in.SingleSnapshot, &out.SingleSnapshot
		*out = new(bool)
		**out = **in
	}
	if in.IgnorePaths != nil {
		in, out := &in.IgnorePaths, &out.IgnorePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildOptions.
func (in *BuildOptions) DeepCopy() *BuildOptions {
	if in == nil {
		return nil
	}
	out := new(BuildOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopySpec) DeepCopyInto(out *CopySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopySpec.
func (in *CopySpec) DeepCopy() *CopySpec {
	if in == nil {
		return nil
	}
	out := new(CopySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FromImage) DeepCopyInto(out *FromImage) {
	*out = *in
	if in.Copy != nil {
		in, out := &in.Copy, &out.Copy
		*out = make([]CopySpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FromImage.
func (in *FromImage) DeepCopy() *FromImage {
	if in == nil {
		return nil
	}
	out := new(FromImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePatch) DeepCopyInto(out *ImagePatch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePatch.
func (in *ImagePatch) DeepCopy() *ImagePatch {
	if in == nil {
		return nil
	}
	out := new(ImagePatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImagePatch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePatchList) DeepCopyInto(out *ImagePatchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImagePatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePatchList.
func (in *ImagePatchList) DeepCopy() *ImagePatchList {
	if in == nil {
		return nil
	}
	out := new(ImagePatchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImagePatchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePatchSpec) DeepCopyInto(out *ImagePatchSpec) {
	*out = *in
	if in.ENV != nil {
		in, out := &in.ENV, &out.ENV
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.APT != nil {
		in, out := &in.APT, &out.APT
		*out = new(AptConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PIP != nil {
		in, out := &in.PIP, &out.PIP
		*out = new(PipConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Shell != nil {
		in, out := &in.Shell, &out.Shell
		*out = make([]ShellStep, len(*in))
		copy(*out, *in)
	}
	if in.FromImages != nil {
		in, out := &in.FromImages, &out.FromImages
		*out = make([]FromImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(UserConfig)
		**out = **in
	}
	if in.Entrypoint != nil {
		in, out := &in.Entrypoint, &out.Entrypoint
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CMD != nil {
		in, out := &in.CMD, &out.CMD
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BuildOptions != nil {
		in, out := &in.BuildOptions, &out.BuildOptions
		*out = new(BuildOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePatchSpec.
func (in *ImagePatchSpec) DeepCopy() *ImagePatchSpec {
	if in == nil {
		return nil
	}
	out := new(ImagePatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePatchStatus) DeepCopyInto(out *ImagePatchStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePatchStatus.
func (in *ImagePatchStatus) DeepCopy() *ImagePatchStatus {
	if in == nil {
		return nil
	}
	out := new(ImagePatchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipConfig) DeepCopyInto(out *PipConfig) {
	*out = *in
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipConfig.
func (in *PipConfig) DeepCopy() *PipConfig {
	if in == nil {
		return nil
	}
	out := new(PipConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellStep) DeepCopyInto(out *ShellStep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellStep.
func (in *ShellStep) DeepCopy() *ShellStep {
	if in == nil {
		return nil
	}
	out := new(ShellStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserConfig) DeepCopyInto(out *UserConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserConfig.
func (in *UserConfig) DeepCopy() *UserConfig {
	if in == nil {
		return nil
	}
	out := new(UserConfig)
	in.DeepCopyInto(out)
	return out
}
