{{- if and .Values.rbac.create .Values.rbac.aggregatedRoles.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "image-patcher.fullname" . }}-imagepatch-admin-role
  labels:
    {{- include "image-patcher.labels" . | nindent 4 }}
rules:
  - apiGroups: ["oms.ogpu.cloud"]
    resources: ["imagepatches"]
    verbs: ["*"]
  - apiGroups: ["oms.ogpu.cloud"]
    resources: ["imagepatches/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "image-patcher.fullname" . }}-imagepatch-editor-role
  labels:
    {{- include "image-patcher.labels" . | nindent 4 }}
rules:
  - apiGroups: ["oms.ogpu.cloud"]
    resources: ["imagepatches"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["oms.ogpu.cloud"]
    resources: ["imagepatches/status"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "image-patcher.fullname" . }}-imagepatch-viewer-role
  labels:
    {{- include "image-patcher.labels" . | nindent 4 }}
rules:
  - apiGroups: ["oms.ogpu.cloud"]
    resources: ["imagepatches"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["oms.ogpu.cloud"]
    resources: ["imagepatches/status"]
    verbs: ["get"]
{{- end }}
